### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by vanzhiganov** [vanzhiganov/backup#43]
- [x] create dockerfile
- [x] add crudini for config management with environment variables
- [ ] crontab in docker image

**Comment by Shubham-Gupta3197** [comment]
@vanzhiganov I can help you with dockerfile. Please assign this issue to me.

**Comment by NehaK275** [comment]
@vanzhiganov Please assign this issue to me

**Comment by vanzhiganov** [comment]
> @vanzhiganov Please assign this issue to me

Hello, you can make pull request with relevant changes

**Comment by NehaK275** [comment]
@vanzhiganov i have raised the PR, please check it.

**Comment by vanzhiganov** [comment]
@NehaK275 thank you. I will test the PR as soon as possible.

**Comment by NehaK275** [comment]
Kindly test it and tell me if any changes required.

**Comment by NehaK275** [comment]
@vanzhiganov have you test it.
